version: '3.8'

services:
  web:
    build: 
      context: yasyt-server
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: yasyt
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  client:
    build:
      context: yasyt-client
      dockerfile: ./Dockerfile
    ports:
      - "3006:3006"
    volumes:
      - ./yasyt-client:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

volumes:
  postgres_data:
